#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-actionview
Version  : 4.2.6
Release  : 12
URL      : https://rubygems.org/downloads/actionview-4.2.6.gem
Source0  : https://rubygems.org/downloads/actionview-4.2.6.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-erubis
BuildRequires : rubygem-rdoc

%description
= Action View
Action View is a framework for handling view template lookup and rendering, and provides
view helpers that assist when building HTML forms, Atom feeds and more.
Template formats that Action View handles are ERB (embedded Ruby, typically
used to inline short Ruby snippets inside HTML), and XML Builder.

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n actionview-4.2.6
gem spec %{SOURCE0} -l --ruby > rubygem-actionview.gemspec

%build
export LANG=C
gem build rubygem-actionview.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
actionview-4.2.6.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/actionview-4.2.6.gem
/usr/lib64/ruby/gems/2.3.0/gems/actionview-4.2.6/CHANGELOG.md
/usr/lib64/ruby/gems/2.3.0/gems/actionview-4.2.6/MIT-LICENSE
/usr/lib64/ruby/gems/2.3.0/gems/actionview-4.2.6/README.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/actionview-4.2.6/lib/action_view.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionview-4.2.6/lib/action_view/base.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionview-4.2.6/lib/action_view/buffers.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionview-4.2.6/lib/action_view/context.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionview-4.2.6/lib/action_view/dependency_tracker.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionview-4.2.6/lib/action_view/digestor.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionview-4.2.6/lib/action_view/flows.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionview-4.2.6/lib/action_view/gem_version.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionview-4.2.6/lib/action_view/helpers.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionview-4.2.6/lib/action_view/helpers/active_model_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionview-4.2.6/lib/action_view/helpers/asset_tag_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionview-4.2.6/lib/action_view/helpers/asset_url_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionview-4.2.6/lib/action_view/helpers/atom_feed_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionview-4.2.6/lib/action_view/helpers/cache_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionview-4.2.6/lib/action_view/helpers/capture_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionview-4.2.6/lib/action_view/helpers/controller_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionview-4.2.6/lib/action_view/helpers/csrf_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionview-4.2.6/lib/action_view/helpers/date_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionview-4.2.6/lib/action_view/helpers/debug_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionview-4.2.6/lib/action_view/helpers/form_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionview-4.2.6/lib/action_view/helpers/form_options_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionview-4.2.6/lib/action_view/helpers/form_tag_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionview-4.2.6/lib/action_view/helpers/javascript_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionview-4.2.6/lib/action_view/helpers/number_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionview-4.2.6/lib/action_view/helpers/output_safety_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionview-4.2.6/lib/action_view/helpers/record_tag_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionview-4.2.6/lib/action_view/helpers/rendering_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionview-4.2.6/lib/action_view/helpers/sanitize_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionview-4.2.6/lib/action_view/helpers/tag_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionview-4.2.6/lib/action_view/helpers/tags.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionview-4.2.6/lib/action_view/helpers/tags/base.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionview-4.2.6/lib/action_view/helpers/tags/check_box.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionview-4.2.6/lib/action_view/helpers/tags/checkable.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionview-4.2.6/lib/action_view/helpers/tags/collection_check_boxes.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionview-4.2.6/lib/action_view/helpers/tags/collection_helpers.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionview-4.2.6/lib/action_view/helpers/tags/collection_radio_buttons.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionview-4.2.6/lib/action_view/helpers/tags/collection_select.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionview-4.2.6/lib/action_view/helpers/tags/color_field.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionview-4.2.6/lib/action_view/helpers/tags/date_field.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionview-4.2.6/lib/action_view/helpers/tags/date_select.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionview-4.2.6/lib/action_view/helpers/tags/datetime_field.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionview-4.2.6/lib/action_view/helpers/tags/datetime_local_field.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionview-4.2.6/lib/action_view/helpers/tags/datetime_select.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionview-4.2.6/lib/action_view/helpers/tags/email_field.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionview-4.2.6/lib/action_view/helpers/tags/file_field.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionview-4.2.6/lib/action_view/helpers/tags/grouped_collection_select.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionview-4.2.6/lib/action_view/helpers/tags/hidden_field.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionview-4.2.6/lib/action_view/helpers/tags/label.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionview-4.2.6/lib/action_view/helpers/tags/month_field.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionview-4.2.6/lib/action_view/helpers/tags/number_field.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionview-4.2.6/lib/action_view/helpers/tags/password_field.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionview-4.2.6/lib/action_view/helpers/tags/placeholderable.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionview-4.2.6/lib/action_view/helpers/tags/radio_button.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionview-4.2.6/lib/action_view/helpers/tags/range_field.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionview-4.2.6/lib/action_view/helpers/tags/search_field.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionview-4.2.6/lib/action_view/helpers/tags/select.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionview-4.2.6/lib/action_view/helpers/tags/tel_field.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionview-4.2.6/lib/action_view/helpers/tags/text_area.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionview-4.2.6/lib/action_view/helpers/tags/text_field.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionview-4.2.6/lib/action_view/helpers/tags/time_field.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionview-4.2.6/lib/action_view/helpers/tags/time_select.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionview-4.2.6/lib/action_view/helpers/tags/time_zone_select.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionview-4.2.6/lib/action_view/helpers/tags/translator.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionview-4.2.6/lib/action_view/helpers/tags/url_field.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionview-4.2.6/lib/action_view/helpers/tags/week_field.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionview-4.2.6/lib/action_view/helpers/text_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionview-4.2.6/lib/action_view/helpers/translation_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionview-4.2.6/lib/action_view/helpers/url_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionview-4.2.6/lib/action_view/layouts.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionview-4.2.6/lib/action_view/locale/en.yml
/usr/lib64/ruby/gems/2.3.0/gems/actionview-4.2.6/lib/action_view/log_subscriber.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionview-4.2.6/lib/action_view/lookup_context.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionview-4.2.6/lib/action_view/model_naming.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionview-4.2.6/lib/action_view/path_set.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionview-4.2.6/lib/action_view/railtie.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionview-4.2.6/lib/action_view/record_identifier.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionview-4.2.6/lib/action_view/renderer/abstract_renderer.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionview-4.2.6/lib/action_view/renderer/partial_renderer.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionview-4.2.6/lib/action_view/renderer/renderer.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionview-4.2.6/lib/action_view/renderer/streaming_template_renderer.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionview-4.2.6/lib/action_view/renderer/template_renderer.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionview-4.2.6/lib/action_view/rendering.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionview-4.2.6/lib/action_view/routing_url_for.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionview-4.2.6/lib/action_view/tasks/dependencies.rake
/usr/lib64/ruby/gems/2.3.0/gems/actionview-4.2.6/lib/action_view/template.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionview-4.2.6/lib/action_view/template/error.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionview-4.2.6/lib/action_view/template/handlers.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionview-4.2.6/lib/action_view/template/handlers/builder.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionview-4.2.6/lib/action_view/template/handlers/erb.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionview-4.2.6/lib/action_view/template/handlers/raw.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionview-4.2.6/lib/action_view/template/html.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionview-4.2.6/lib/action_view/template/resolver.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionview-4.2.6/lib/action_view/template/text.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionview-4.2.6/lib/action_view/template/types.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionview-4.2.6/lib/action_view/test_case.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionview-4.2.6/lib/action_view/testing/resolvers.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionview-4.2.6/lib/action_view/version.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionview-4.2.6/lib/action_view/view_paths.rb
/usr/lib64/ruby/gems/2.3.0/specifications/actionview-4.2.6.gemspec
